vars:
  - my_project_name: YOLOv8n_custom_1

stages:
  train:
    cmd: 
      - python src/train_yolo.py ${YOLOv8n_custom_1.train} --train-data data/train/images/ --val-data data/valid/images/  --expname ${my_project_name}
    deps:
      - src/train_yolo.py
      - data/train/images/
      - data/train/labels/
      - src/yolov8/
      - data/valid/images/
      - data/valid/labels/
    params:
      - YOLOv8n_custom_1
    outs:
      - models/${my_project_name}/
      - runs/train/${my_project_name}/
  validate:
      cmd: python src/val_yolo.py  ${YOLOv8n_custom_1.validate} --expname ${my_project_name}
      deps:
      - src/val_yolo.py
      - data/train/images/
      - data/train/labels/
      - data/valid/images/
      - data/valid/labels/
      - data/test/images/
      - data/test/labels/
      - models/${my_project_name}/
      - src/yolov8/
      params:
      - YOLOv8n_custom_1
      outs:
      - validations/${my_project_name}/
      - runs/val/${my_project_name}/
